image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787
    - formulahendry.auto-close-tag@0.5.6
    - eventyret.bootstrap-4-cdn-snippet@1.3.0
# bootstrap-4-cdn-snippet@1.3.0
